<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class FormSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('form')->insert([
            ['travel_order_id' => 1, 'name_id' => 4, 'position_id' => 4, 'division_id' => 5, 'station' => 'MGB-X', 'destination' => 'Macanhan Carmen CDO', 'purpose' => 'Go home', 'departure' => '2024-03-07', 'arrival' => '2024-03-08', 'signature1' => NULL, 'signature2' => NULL, 'pdea' => NULL, 'ala' => NULL, 'appropriations' => NULL, 'remarks' => NULL, 'date' => '2024-03-06', 'note' => NULL, 'sname' => NULL, 'sdiv' => NULL, 'to_num' => NULL, 'initial' => 0, 'intervals' => NULL, 'aor' => NULL],
            ['travel_order_id' => 2, 'name_id' => 4, 'position_id' => 4, 'division_id' => 5, 'station' => 'MGB-X', 'destination' => 'Macanhan Carmen CDO', 'purpose' => 'Go home', 'departure' => '2024-03-07', 'arrival' => '2024-03-08', 'signature1' => NULL, 'signature2' => NULL, 'pdea' => NULL, 'ala' => NULL, 'appropriations' => NULL, 'remarks' => NULL, 'date' => '2024-03-06', 'note' => NULL, 'sname' => NULL, 'sdiv' => NULL, 'to_num' => NULL, 'initial' => 0, 'intervals' => NULL, 'aor' => NULL],
            ['travel_order_id' => 3, 'name_id' => 3, 'position_id' => 3, 'division_id' => 3, 'station' => 'MGB-X', 'destination' => 'Iponan CDO', 'purpose' => 'River', 'departure' => '2024-03-08', 'arrival' => '2024-03-09', 'signature1' => 'images/QLIqYuX8PchVJygyAvN1uyUAdHUsSVTQHm6RihI9.jpg', 'signature2' => NULL, 'pdea' => NULL, 'ala' => NULL, 'appropriations' => NULL, 'remarks' => NULL, 'date' => '2024-03-07', 'note' => NULL, 'sname' => NULL, 'sdiv' => NULL, 'to_num' => NULL, 'initial' => 0, 'intervals' => NULL, 'aor' => NULL],
            ['travel_order_id' => 7, 'name_id' => 4, 'position_id' => 4, 'division_id' => 4, 'station' => 'MGB-X', 'destination' => 'Macasandig', 'purpose' => 'Visit', 'departure' => '2024-03-11', 'arrival' => '2024-03-11', 'signature1' => NULL, 'signature2' => NULL, 'pdea' => NULL, 'ala' => NULL, 'appropriations' => NULL, 'remarks' => NULL, 'date' => '2024-03-07', 'note' => NULL, 'sname' => NULL, 'sdiv' => NULL, 'to_num' => NULL, 'initial' => 0, 'intervals' => NULL, 'aor' => NULL],
            ['travel_order_id' => 8, 'name_id' => 2, 'position_id' => 2, 'division_id' => 2, 'station' => 'MGB-X', 'destination' => 'Talisayan', 'purpose' => 'Muuli kay mingaw', 'departure' => '2024-03-09', 'arrival' => '2024-03-10', 'signature1' => NULL, 'signature2' => NULL, 'pdea' => NULL, 'ala' => NULL, 'appropriations' => NULL, 'remarks' => NULL, 'date' => '2024-03-07', 'note' => NULL, 'sname' => NULL, 'sdiv' => NULL, 'to_num' => NULL, 'initial' => 0, 'intervals' => NULL, 'aor' => NULL],
            ['travel_order_id' => 9, 'name_id' => 10, 'position_id' => 9, 'division_id' => 5, 'station' => 'MGB-X', 'destination' => 'Medina', 'purpose' => 'Maligo Dagat', 'departure' => '2024-03-08', 'arrival' => '2024-03-09', 'signature1' => NULL, 'signature2' => NULL, 'pdea' => NULL, 'ala' => NULL, 'appropriations' => NULL, 'remarks' => NULL, 'date' => '2024-03-07', 'note' => NULL, 'sname' => NULL, 'sdiv' => NULL, 'to_num' => NULL, 'initial' => 0, 'intervals' => NULL, 'aor' => NULL],
            ['travel_order_id' => 10, 'name_id' => 16, 'position_id' => 10, 'division_id' => 4, 'station' => 'MGB-X', 'destination' => 'Bisdak', 'purpose' => 'Palit Vape', 'departure' => '2024-03-09', 'arrival' => '2024-03-10', 'signature1' => NULL, 'signature2' => NULL, 'pdea' => NULL, 'ala' => NULL, 'appropriations' => NULL, 'remarks' => NULL, 'date' => '2024-03-07', 'note' => NULL, 'sname' => NULL, 'sdiv' => NULL, 'to_num' => NULL, 'initial' => 0, 'intervals' => NULL, 'aor' => NULL],
            ['travel_order_id' => 11, 'name_id' => 1, 'position_id' => 1, 'division_id' => 1, 'station' => 'MGB-X', 'destination' => 'asd', 'purpose' => 'eqweqwe', 'departure' => '2024-04-02', 'arrival' => '2024-02-26', 'signature1' => NULL, 'signature2' => NULL, 'pdea' => NULL, 'ala' => NULL, 'appropriations' => NULL, 'remarks' => NULL, 'date' => '2024-03-08', 'note' => NULL, 'sname' => NULL, 'sdiv' => NULL, 'to_num' => NULL, 'initial' => 0, 'intervals' => NULL, 'aor' => NULL],
            ['travel_order_id' => 12, 'name_id' => 6, 'position_id' => 6, 'division_id' => 3, 'station' => 'MGB-X', 'destination' => 'asd', 'purpose' => 'asdsadasdasd', 'departure' => '2024-03-04', 'arrival' => '2024-03-25', 'signature1' => NULL, 'signature2' => NULL, 'pdea' => NULL, 'ala' => NULL, 'appropriations' => NULL, 'remarks' => NULL, 'date' => '2024-03-08', 'note' => NULL, 'sname' => NULL, 'sdiv' => NULL, 'to_num' => NULL, 'initial' => 0, 'intervals' => NULL, 'aor' => NULL],
            ['travel_order_id' => 13, 'name_id' => 15, 'position_id' => 13, 'division_id' => 2, 'station' => 'MGB-X', 'destination' => 'asdsad', 'purpose' => 'asdasd', 'departure' => '2024-03-19', 'arrival' => '2024-03-17', 'signature1' => NULL, 'signature2' => NULL, 'pdea' => NULL, 'ala' => NULL, 'appropriations' => NULL, 'remarks' => NULL, 'date' => '2024-03-08', 'note' => NULL, 'sname' => NULL, 'sdiv' => NULL, 'to_num' => NULL, 'initial' => 0, 'intervals' => NULL, 'aor' => NULL],
            ['travel_order_id' => 14, 'name_id' => 12, 'position_id' => 5, 'division_id' => 4, 'station' => 'MGB-X', 'destination' => 'Gingoog', 'purpose' => 'Gumawa sa tawag ni Boss', 'departure' => '2024-03-11', 'arrival' => '2024-03-14', 'signature1' => NULL, 'signature2' => NULL, 'pdea' => NULL, 'ala' => NULL, 'appropriations' => NULL, 'remarks' => NULL, 'date' => '2024-03-08', 'note' => NULL, 'sname' => NULL, 'sdiv' => NULL, 'to_num' => NULL, 'initial' => 0, 'intervals' => NULL, 'aor' => NULL],
            ['travel_order_id' => 15, 'name_id' => 9, 'position_id' => 7, 'division_id' => 3, 'station' => 'MGB-X', 'destination' => 'Malingin', 'purpose' => 'on call', 'departure' => '2024-03-14', 'arrival' => '2024-03-15', 'signature1' => NULL, 'signature2' => NULL, 'pdea' => NULL, 'ala' => NULL, 'appropriations' => NULL, 'remarks' => NULL, 'date' => '2024-03-08', 'note' => NULL, 'sname' => NULL, 'sdiv' => NULL, 'to_num' => NULL, 'initial' => 0, 'intervals' => NULL, 'aor' => NULL],
            ['travel_order_id' => 16, 'name_id' => 11, 'position_id' => 11, 'division_id' => 1, 'station' => 'MGB-X', 'destination' => 'Gingoog', 'purpose' => 'Maligo dagat', 'departure' => '2024-03-14', 'arrival' => '2024-03-15', 'signature1' => NULL, 'signature2' => NULL, 'pdea' => NULL, 'ala' => NULL, 'appropriations' => NULL, 'remarks' => NULL, 'date' => '2024-03-08', 'note' => NULL, 'sname' => NULL, 'sdiv' => NULL, 'to_num' => NULL, 'initial' => 0, 'intervals' => NULL, 'aor' => NULL],
            ['travel_order_id' => 17, 'name_id' => 8, 'position_id' => 6, 'division_id' => 2, 'station' => 'MGB-X', 'destination' => 'Macasandig', 'purpose' => 'visit', 'departure' => '2024-03-15', 'arrival' => '2024-03-16', 'signature1' => NULL, 'signature2' => NULL, 'pdea' => NULL, 'ala' => NULL, 'appropriations' => NULL, 'remarks' => NULL, 'date' => '2024-03-08', 'note' => NULL, 'sname' => NULL, 'sdiv' => NULL, 'to_num' => NULL, 'initial' => 0, 'intervals' => NULL, 'aor' => NULL],
            ['travel_order_id' => 18, 'name_id' => 7, 'position_id' => 5, 'division_id' => 1, 'station' => 'MGB-X', 'destination' => 'Minaog', 'purpose' => 'Inspect site', 'departure' => '2024-03-15', 'arrival' => '2024-03-16', 'signature1' => NULL, 'signature2' => NULL, 'pdea' => NULL, 'ala' => NULL, 'appropriations' => NULL, 'remarks' => NULL, 'date' => '2024-03-08', 'note' => NULL, 'sname' => NULL, 'sdiv' => NULL, 'to_num' => NULL, 'initial' => 0, 'intervals' => NULL, 'aor' => NULL],
            ['travel_order_id' => 19, 'name_id' => 20, 'position_id' => 20, 'division_id' => 1, 'station' => 'MGB-X', 'destination' => 'Poblacion', 'purpose' => 'Submit report', 'departure' => '2024-03-15', 'arrival' => '2024-03-16', 'signature1' => NULL, 'signature2' => NULL, 'pdea' => NULL, 'ala' => NULL, 'appropriations' => NULL, 'remarks' => NULL, 'date' => '2024-03-08', 'note' => NULL, 'sname' => NULL, 'sdiv' => NULL, 'to_num' => NULL, 'initial' => 0, 'intervals' => NULL, 'aor' => NULL],
            ['travel_order_id' => 20, 'name_id' => 14, 'position_id' => 14, 'division_id' => 2, 'station' => 'MGB-X', 'destination' => 'Claveria', 'purpose' => 'Meeting', 'departure' => '2024-03-16', 'arrival' => '2024-03-17', 'signature1' => NULL, 'signature2' => NULL, 'pdea' => NULL, 'ala' => NULL, 'appropriations' => NULL, 'remarks' => NULL, 'date' => '2024-03-08', 'note' => NULL, 'sname' => NULL, 'sdiv' => NULL, 'to_num' => NULL, 'initial' => 0, 'intervals' => NULL, 'aor' => NULL],
            ['travel_order_id' => 21, 'name_id' => 5, 'position_id' => 5, 'division_id' => 3, 'station' => 'MGB-X', 'destination' => 'Valencia', 'purpose' => 'Inspection', 'departure' => '2024-03-16', 'arrival' => '2024-03-17', 'signature1' => NULL, 'signature2' => NULL, 'pdea' => NULL, 'ala' => NULL, 'appropriations' => NULL, 'remarks' => NULL, 'date' => '2024-03-08', 'note' => NULL, 'sname' => NULL, 'sdiv' => NULL, 'to_num' => NULL, 'initial' => 0, 'intervals' => NULL, 'aor' => NULL],
        ]);
    }
}
